root = "."
tmp_dir = "tmp"

[build]
  cmd = "env -u GOROOT go build -o ./tmp/wiki ./cmd/wiki"
  entrypoint = "./tmp/wiki"
  include_ext = ["go", "html", "css"]
  include_dir = ["cmd", "internal", "web"]
  exclude_dir = ["tmp", "data", ".git"]

[log]
  time = true
